export class AudioManager{
  constructor(){this.ctx=null;this.master=null;this.engine=null;this.engineGain=null;this.wind=null;this.windGain=null;this.enabled=true}
  async init(){if(this.ctx)return;const C=window.AudioContext||window.webkitAudioContext;if(!C){this.enabled=false;return}this.ctx=new C();this.master=this.ctx.createGain();this.master.gain.value=.5;this.master.connect(this.ctx.destination);this._engine();this._wind();if(this.ctx.state==='suspended')await this.ctx.resume()}
  _engine(){const c=this.ctx;this.engine=c.createOscillator();this.engine.type='sawtooth';this.engine.frequency.value=60;const low=c.createBiquadFilter();low.type='lowpass';low.frequency.value=460;this.engineGain=c.createGain();this.engineGain.gain.value=.0001;this.engine.connect(low);low.connect(this.engineGain);this.engineGain.connect(this.master);this.engine.start()}
  _wind(){const c=this.ctx;const buffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;this.wind=c.createBufferSource();this.wind.buffer=buffer;this.wind.loop=true;const hp=c.createBiquadFilter();hp.type='highpass';hp.frequency.value=700;this.windGain=c.createGain();this.windGain.gain.value=.0001;this.wind.connect(hp);hp.connect(this.windGain);this.windGain.connect(this.master);this.wind.start()}
  update(speed,throttle,nitro){if(!this.ctx||!this.enabled)return;const t=this.ctx.currentTime;const rpm=55+Math.min(210,speed*1.55)+Math.abs(throttle)*38;this.engine.frequency.setTargetAtTime(rpm,t,.045);this.engineGain.gain.setTargetAtTime(.028+Math.min(.12,speed/900)+Math.abs(throttle)*.025+(nitro?.035:0),t,.06);this.windGain.gain.setTargetAtTime(Math.max(.0001,Math.min(.09,(speed-35)/1300)),t,.1)}
  beep(freq=660,dur=.08,gain=.08){if(!this.ctx||!this.enabled)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime;o.type='sine';o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(freq*1.18,t+dur);g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+dur+.02)}
  impact(intensity=.5){if(!this.ctx||!this.enabled)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime;o.type='square';o.frequency.setValueAtTime(110,t);o.frequency.exponentialRampToValueAtTime(34,t+.12);g.gain.setValueAtTime(.025+.07*intensity,t);g.gain.exponentialRampToValueAtTime(.0001,t+.14);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+.15)}
  success(){this.beep(620,.08,.08);setTimeout(()=>this.beep(820,.09,.07),85);setTimeout(()=>this.beep(1050,.12,.06),170)}
  setVolume(v){if(this.master&&this.ctx)this.master.gain.setTargetAtTime(v,this.ctx.currentTime,.05)}
}
